name: spin_wheel_game
description: A spin wheel game in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_fortune_wheel: ^1.3.1
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/spin.mp3